% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Simple Regression Analysis},
  pdfauthor={SW},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Simple Regression Analysis}
\author{SW}
\date{2022/7/10}

\begin{document}
\maketitle

\hypertarget{key-terms}{%
\subsection{Key terms}\label{key-terms}}

\begin{itemize}
\tightlist
\item
  Dependent variable
\item
  Explanatory variable, independent variable, regressor
\item
  Disturbance term
\item
  Residual
\item
  Residual sum of squares, \emph{RSS}
\item
  Ordinary least squares, \emph{OLS}
\item
  Normal equations
\item
  Demeaning
\end{itemize}

\hypertarget{the-simple-linear-model}{%
\subsection{1. The simple linear model}\label{the-simple-linear-model}}

\textbf{The model}:

\[Y_{i}=\beta_{1}+\beta_{2}X_{i}+u_{i}\] where \(Y\) is usually
described as the \textbf{dependent variable}, and \(X\) as the
\textbf{explanatory variable} or \textbf{independent variable} or the
\textbf{regressor}. In statistical analysis, one generally
acknowledgesthe fact that the relationship is not exact by explicitly
including in it a random factor known as the \textbf{disturbance term},
\(\mu_{i}\).

\textbf{The fitted model}:

\[\hat{Y_{i}}=\hat{\beta_{1}}+\hat{\beta_{2}}X_{i}\]

The difference between the actual value of \(Y_{i}\) and the fitted
value \$\hat{Y_{i}}, in observation \(i\) is known as the
\textbf{residual} in the observation \(i\). It will be denoted
\hat{\mu_{i}}:

\[\hat{u}_{i}=Y_{i}-\hat{Y_{i}}\]

\hypertarget{derivation-of-the-regression-coefficients}{%
\subsection{2. Derivation of the regression
coefficients}\label{derivation-of-the-regression-coefficients}}

We use the \textbf{least squares} criterion to choose
\(\hat{\beta_{1}}\) amd \(\hat{\beta_{2}}\) so as to minimize
\emph{\textbf{RSS}}, the \textbf{residual sum of squares} (sum of the
squares of the residuals).

\[RSS=\sum_{i=1}^{n}{\hat{u}_{i}}^2\] This is usually referred to as
\textbf{ordinary least squares} and abbreviated \emph{\textbf{OLS}}.\\
The square of the residual in observaiont \(i\) interms of
\(\hat{\beta_{1}}\) and \hat{\beta_{2}}\$, and the data on \(X\) and
\(Y\):

\begin{eqnarray}
{\hat{u}_{i}}^2 &=&(Y_i-\hat{Y}_{i})^2 =(Y_i-\hat{\beta}_{1}-\hat{\beta}_{2}X_i)^2 \\

&=& Y_i^2+\hat{\beta}_{1}^2+\hat{\beta}_{2}^2X_i^2-2\hat{\beta}_{1}Y_i-2\hat{\beta}_{2}X_iY_i+2\hat{\beta}_{1}\hat{\beta}_{2}X_i \\
\end{eqnarray}

(For formatting of the above equation array, see the website
\href{https://www.stat.cmu.edu/~cshalizi/rmarkdown/}{Using R Markdown
for Class Reports} by Cosma Shalizi for more information.)\\

Summing over all the \(n\) observations, we can write \emph{RSS} as

\[RSS=\sum_{i=1}^{n}Y_i^2+n\hat{\beta}_{1}^2+\hat{\beta}_{2}^2\sum_{i=1}^{n}X_i^2-2\hat{\beta}_{1}\sum_{i=1}^{n}Y_i-2\hat{\beta}_{2}\sum_{i=1}^{n}X_iY_i+2\hat{\beta}_{1}\hat{\beta}_{2}\sum_{i=1}^{n}X_i\]

We find the particular values of \(\hat{\beta}_{1}\) and
\(\hat{\beta}_{2}\) by minimize \emph{RSS}. The partial differentials of
\emph{RSS} with respect to \(\hat{\beta}_{1}\) and \(\hat{\beta}_{2}\)
are:

\[\frac{\partial{RSS}}{\partial{\hat{\beta}_{1}}}=2n\hat{\beta}_{1}-2\sum_{i=1}^{n}Y_i+2\hat{\beta}_{2}\sum_{i=1}^{n}X_i\]

\[\frac{\partial{RSS}}{\partial{\hat{\beta}_{2}}}=2\hat{\beta}_{2}\sum_{i=1}^{n}X_i^2-2\sum_{i=1}^{n}X_iY_i+2\hat{\beta}_{1}\sum_{i=1}^{n}X_i\]

The values of \(\hat{\beta}_{1}\) and \(\hat{\beta}_{2}\) that minimize
\emph{RSS} must satisfy the first-order conditions

\begin{equation}
\frac{\partial{RSS}}{\partial{\hat{\beta}_{1}}}=0
\quad\mathrm{and}\quad
\frac{\partial{RSS}}{\partial{\hat{\beta}_{2}}}=0
\end{equation}

(Please see the website
\url{https://tex.stackexchange.com/questions/288222/two-equations-in-one-line}
for more information on how to format two equations on one line.)

Hence
\[2n\hat{\beta}_{1}-2\sum_{i=1}^{n}Y_i+2\hat{\beta}_{2}\sum_{i=1}^{n}X_i=0\]
\[2\hat{\beta}_{2}\sum_{i=1}^{n}X_i^2-2\sum_{i=1}^{n}X_iY_i+2\hat{\beta}_{1}\sum_{i=1}^{n}X_i=0\]
These equations are known as the \textbf{normal equations} for the
regression coefficients.\\
Solving the normal equations and noting that

\begin{equation}
\overline{X}=\frac{1}{n}\sum_{i=1}^{n}X_i
\quad\mathrm{and}\quad
\overline{Y}=\frac{1}{n}\sum_{i=1}^{n}Y_i
\end{equation}

and hence

\[\hat{\beta}_{1}=\overline{Y}-\hat{\beta}_{2}\overline{X}\]
\[\hat{\beta}_{2}=\frac{\sum_{i=1}^{n}X_iY_i-n\overline{X}\overline{Y}}{\sum_{i=1}^{n}X_i^2-n\overline{X}^2}=\frac{\sum_{i=1}^{n}(X_i-\overline{X})(Y_i-\overline{Y})}{\sum_{i=1}^{n}(X_i-\overline{X})^2}\]

\hypertarget{an-example}{%
\subsection{3. An example}\label{an-example}}

The following example is adopted from an example in p.~98 of the text
book. Hourly earnings in 2011, \texttt{EARNINGS}, measured in dollars,
are regressed on schooling, \texttt{S}, measured as highest grade
completed, for 500 respondents from the US National Longitudinal Survey
of Youth 1997-.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# EARNINGS regress on schooling}
\NormalTok{eawe21 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}./Data/EAWE21.csv\textquotesingle{}}\NormalTok{, }\AttributeTok{header=}\NormalTok{T)   }\CommentTok{\# Import data}
\NormalTok{linear\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(EARNINGS }\SpecialCharTok{\textasciitilde{}}\NormalTok{ S, }\AttributeTok{data =}\NormalTok{ eawe21)     }\CommentTok{\# Run the model}
\FunctionTok{summary}\NormalTok{(linear\_model)                               }\CommentTok{\# The result}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = EARNINGS ~ S, data = eawe21)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -20.079  -6.726  -2.203   3.451  79.037 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   0.7647     2.8038   0.273    0.785    
## S             1.2657     0.1855   6.824 2.58e-11 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 11.36 on 498 degrees of freedom
## Multiple R-squared:  0.08551,    Adjusted R-squared:  0.08368 
## F-statistic: 46.57 on 1 and 498 DF,  p-value: 2.579e-11
\end{verbatim}

The regression output gives the estimates of the intercept and the
coefficient of \texttt{S}, and thus the following fitted equation:

\[\hat{EARNINGS}=0.76+1.27S\] Interpreting the equation literally, the
slope coefficient indicates that, as \texttt{S} increases by one unit,
\texttt{EARNINGS} increases by 1.27 units. This implies that hourly
earnings increase by \$1.27 for every extra year of schooling.

\hypertarget{demeaning}{%
\paragraph{Demeaning}\label{demeaning}}

Often the intercept in a regression equation has no sensible
interpretation because \(X=0\) is distant from the data range. The wage
equation above is an example, with the intercept being implausibly
low.\\
Sometimes it is useful to deal with the problem by defining \(X^*\) as
the deviation of \(X\) about its sample mean

\[X_{i}^{*}=X_i-\overline{X}\] and regressing \(Y\) on \(X^*\). The
slope coefficient will not be affected, but the intercept will now be
the fitted value of \(Y\) at the sample mean of \(X\).\\
The following R code gives the descriptive statistics of \texttt{S}.
This gives the mean years of schooling was 14.87.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Descriptive statistics for S}
\FunctionTok{summary}\NormalTok{(eawe21}\SpecialCharTok{$}\NormalTok{S)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    8.00   12.00   15.00   14.87   17.00   20.00
\end{verbatim}

We then regress \texttt{EARNINGS} on the demeaned variable
\texttt{SDEV}, where \[SDEV_i=S_i-\overline{S}\]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create the demeaned variable SDEV}
\FunctionTok{library}\NormalTok{(tidyverse)                  }\CommentTok{\# Load the required package}

\NormalTok{eawe21\_dm }\OtherTok{\textless{}{-}}\NormalTok{ eawe21 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{SDEV =}\NormalTok{ S }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(S)) }\SpecialCharTok{\%\textgreater{}\%}    \CommentTok{\# Create the demeaned variable}
  \FunctionTok{select}\NormalTok{(EARNINGS, S, SDEV)         }\CommentTok{\# Select the required columns}

\CommentTok{\# EARNINGS regress on the demeaned variable SDEV}
\NormalTok{linear\_model\_dm }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(EARNINGS }\SpecialCharTok{\textasciitilde{}}\NormalTok{ SDEV, }\AttributeTok{data =}\NormalTok{ eawe21\_dm)     }\CommentTok{\# Run the model}
\FunctionTok{summary}\NormalTok{(linear\_model\_dm)                                     }\CommentTok{\# The result      }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = EARNINGS ~ SDEV, data = eawe21_dm)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -20.079  -6.726  -2.203   3.451  79.037 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  19.5808     0.5082  38.528  < 2e-16 ***
## SDEV          1.2657     0.1855   6.824 2.58e-11 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 11.36 on 498 degrees of freedom
## Multiple R-squared:  0.08551,    Adjusted R-squared:  0.08368 
## F-statistic: 46.57 on 1 and 498 DF,  p-value: 2.579e-11
\end{verbatim}

From the regression results, we can see that the coefficient for
\texttt{SDEV} is 1.27, which is the same as the coefficient of
\texttt{S} in the original wage equation. However, this regression
further predicts that the hourly earnings is \$19.58 for the mean years
of schooling of 14.87.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# EARNINGS regress on schooling}
\NormalTok{eawe21 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}./Data/EAWE21.csv\textquotesingle{}}\NormalTok{, }\AttributeTok{header=}\NormalTok{T)   }\CommentTok{\# Import data}
\NormalTok{linear\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(EARNINGS }\SpecialCharTok{\textasciitilde{}}\NormalTok{ S, }\AttributeTok{data =}\NormalTok{ eawe21)     }\CommentTok{\# Run the model}
\FunctionTok{summary}\NormalTok{(linear\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = EARNINGS ~ S, data = eawe21)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -20.079  -6.726  -2.203   3.451  79.037 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   0.7647     2.8038   0.273    0.785    
## S             1.2657     0.1855   6.824 2.58e-11 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 11.36 on 498 degrees of freedom
## Multiple R-squared:  0.08551,    Adjusted R-squared:  0.08368 
## F-statistic: 46.57 on 1 and 498 DF,  p-value: 2.579e-11
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(linear\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: EARNINGS
##            Df Sum Sq Mean Sq F value    Pr(>F)    
## S           1   6014  6014.0  46.568 2.579e-11 ***
## Residuals 498  64315   129.1                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# EARNINGS regress on schooling}
\NormalTok{eawe21 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}./Data/EAWE21.csv\textquotesingle{}}\NormalTok{, }\AttributeTok{header=}\NormalTok{T)   }\CommentTok{\# Import data}
\FunctionTok{lm}\NormalTok{(EARNINGS }\SpecialCharTok{\textasciitilde{}}\NormalTok{ S, }\AttributeTok{data =}\NormalTok{ eawe21) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  anova}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: EARNINGS
##            Df Sum Sq Mean Sq F value    Pr(>F)    
## S           1   6014  6014.0  46.568 2.579e-11 ***
## Residuals 498  64315   129.1                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

(Please the website \url{https://rc2e.com/linearregressionandanova} for
more information on regression output.)

\end{document}
